version: "3.8"
services:
  server:
    build:
      context: ./server
    image: server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
    volumes:
      - ./server:/app

  web_client:
    build:
      context: ./web_client
    volumes:
      - ./web_client:/core
    ports:
      - "3000:3000"
    image: web_client
    depends_on:
      - server

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
